# Generated by Django 4.1 on 2022-09-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
    ]
