# Generated by Django 4.1 on 2022-09-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ric', '0002_alter_subject_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_date']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-end_date']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['education', '-weight']},
        ),
    ]
