# Generated by Django 4.1 on 2022-09-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ric', '0003_alter_education_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ric.education'),
        ),
        migrations.AlterField(
            model_name='location',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ric.experience'),
        ),
    ]
