# Generated by Django 4.1 on 2022-09-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ric', '0004_alter_location_education_alter_location_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='summary',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
